//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BusinessCardBinder.rc에서 사용되고 있습니다.
//
#define IDD_BUSINESSCARDBINDERFORM      101
#define IDD_FINDINGFORM                 103
#define IDD_TAKEINFORM                  105
#define IDD_TAKEOUTFORM                 107
#define IDD_ZIPCODEFORM                 108
#define IDC_STATIC_BUSINESSCARD         1001
#define IDC_PERSONAL                    1002
#define IDC_COMPANY                     1003
#define IDC_STATIC_NAME                 1004
#define IDC_STATIC_POSITION             1005
#define IDC_STATIC_EMAIL                1006
#define IDC_STATIC_TELEPHONENUMBER      1007
#define IDC_STATIC_NAMES                1008
#define IDC_STATIC_ADDRESS              1009
#define IDC_STATIC_TELEPHONENUMBERS     1010
#define IDC_STATIC_FAX                  1011
#define IDC_STATIC_URL                  1012
#define IDC_STATIC_PERSONALNAME         1013
#define IDC_LIST_ADDRESSES              1013
#define IDC_STATIC_PERSONALPOSITION     1014
#define IDC_STATIC_TERMS                1014
#define IDC_STATIC_PERSONALTELEPHONENUMBER 1015
#define IDC_STATIC_PERSONALEMAIL        1016
#define IDC_STATIC_COMPANYADDRESS       1017
#define IDC_STATIC_COMPANYFAX           1018
#define IDC_STATIC_COMPANYURL           1019
#define IDC_STATIC_COMPANYNAME          1020
#define IDC_STATIC_COMPANYTELEPHONENUMBER 1021
#define IDC_STATIC_MENU                 1021
#define IDC_BUTTON_TAKEIN               1022
#define IDC_BUTTON_FIND                 1023
#define IDC_BUTTON_ARRANGE              1024
#define IDC_BUTTON_SELECTION            1024
#define IDC_BUTTON_SELECT               1024
#define IDC_EDIT_AREA                   1024
#define IDC_BUTTON_TAKEOUT              1025
#define IDC_STATIC_EXAMPLE              1025
#define IDC_BUTTON_FIRST                1026
#define IDC_STATIC_AREA                 1026
#define IDC_BUTTON_PREVIOUS             1027
#define IDC_STATIC_CONDITION            1027
#define IDC_BUTTON_LAST                 1028
#define IDC_STATIC_SEARCHNAME           1028
#define IDC_STATIC_FINDINGFORM_NAME     1028
#define IDC_BUTTON_NEXT                 1029
#define IDC_EDIT_NAME                   1029
#define IDC_STATIC_PERSONAL             1030
#define IDC_STATIC_COMPANY              1031
#define IDC_STATIC_COMPANY_NAME         1032
#define IDC_STATIC_PRINT_COMPANY_NAME   1033
#define IDC_STATIC_PRINT_COMPANY_ADDRESS 1034
#define IDC_STATIC_PRINT_COMPANY_TELEPHONENUMBER 1035
#define IDC_STATIC_PRINT_COMPANY_FAXNUMBER 1036
#define IDC_STATIC_PRINT_COMPANY_URL    1037
#define IDC_STATIC_COMPANY_URL          1038
#define IDC_STATIC_COMPANY_FAXNUMBER    1039
#define IDC_STATIC_COMPANY_TELEPHONENUMBERS 1040
#define IDC_STATIC_COMPANY_ADDRESS      1041
#define IDC_STATIC_PERSONAL_NAME        1042
#define IDC_STATIC_PERSONAL_POSITION    1043
#define IDC_STATIC_PERSONAL_TELEPHONENUMBER 1044
#define IDC_STATIC_PERSONAL_EMAILADDRESS 1045
#define IDC_STATIC_PRINT_PERSONAL_EMAILADDRESS 1046
#define IDC_STATIC_PRINT_PERSONAL_TELEPHONENUMBER 1047
#define IDC_STATIC_PRINT_PERSONAL_POSITION 1048
#define IDC_STATIC_PRINT_PERSONAL_NAME  1049
#define IDC_BUTTON_PREVIOUS2            1050
#define IDC_BUTTON_LAST2                1051
#define IDC_STATIC_PERSONAL_EMAIL       1052
#define IDC_BUTTON_NEXT2                1052
#define IDC_EDIT_PERSONAL_TELEPHONENUMBER 1055
#define IDC_EDIT_CELLPHONENUMBER        1055
#define IDC_EDIT_EMAILID                1056
#define IDC_EDIT_COMPANY_ADDRESS        1058
#define IDC_EDIT_ADDRESS                1058
#define IDC_EDIT_COMPANY_TELEPHONENUMBER 1059
#define IDC_EDIT_TELEPHONENUMBER        1059
#define IDC_EDIT_COMPANY_FAXNUMBER      1060
#define IDC_EDIT_FAXNUMBER              1060
#define IDC_EDIT_COMPANY_URL            1061
#define IDC_EDIT_URL                    1061
#define IDC_COMBO_POSITION              1062
#define IDC_STATIC_AT                   1063
#define IDC_COMBO_EMAILDOMAIN           1064
#define IDC_EDIT_COMPANY_NAME           1065
#define IDC_EDIT_COMPANYNAME            1065
#define IDC_EDIT_PERSONAL_NAME          1066
#define IDC_STATIC_DATA_PERSONAL_NAME   1067
#define IDC_STATIC_DATA_PERSONAL_POSITION 1068
#define IDC_STATIC_DATA_PERSONAL_TELEPHONENUMBER 1069
#define IDC_STATIC_DATA_PERSONAL_EMAILADDRESS 1070
#define IDC_STATIC_DATA_COMPANY_NAME    1071
#define IDC_STATIC_DATA_COMPANY_ADDRESS 1072
#define IDC_STATIC_DATA_COMPANY_TELEPHONENUMBER 1073
#define IDC_STATIC_DATA_COMPANY_FAXNUMBER 1074
#define IDC_STATIC_DATA_COMPANY_URL     1075
#define IDC_BUTTON_ZIPCODE              1077
#define IDC_STATIC_CELLPHONENUMBER      1079
#define IDC_STATIC_EMAILADDRESS         1080
#define IDC_STATIC_FAXNUMBER            1081
#define IDC_TREE1                       1083
#define IDC_TREE_COMPANIES              1083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
